#!/bin/sh

# This script is used to download the upstream source for libva and
# generate it into an orig source tarball for Debian.

# Common variables used to ease maintenance of this script
I965_VERSION="1.0.15"
I965_TARBALL="intel-driver-$I965_VERSION.tar.gz"
I965_ORIG_TARBALL="intel-driver_$I965_VERSION.orig.tar.gz"
USAGE="\n\
This script is used to generate the orig tarball used in building\n\
Debian packages for intel-driver-$I965_VERSION.\n\
Usage: i965-get-orig-source [OPTION]\n\
\n\
 -h, --help                 Display this help message.\n"

while [ "$#" -gt "0" ]
do
    case "$1" in
        -h|--help|*)
            echo "${USAGE}"
            exit 1
            ;;
    esac
done

make_current_tarball() {
    # Download the tarball if it's not available in the current directory
    [ -f $I965_TARBALL ] || \
        wget -c http://cgit.freedesktop.org/vaapi/intel-driver/snapshot/$I965_TARBALL

    # Extract tarball and run 'autoreconf -vif'
    echo "Extracting tarball and running 'autoreconf -vif'"
    tar -zxf $I965_TARBALL
    cd intel-driver-$I965_VERSION
    autoreconf -vif
    cd ..

    # Remove temp files and other cruft from source tarball
    # The find command snippet here was taken from debhelper's dh_clean command
    # with some modification to delete more unneeded files.
    echo "Removing temp files and other cruft from source tarball"
    find intel-driver-$I965_VERSION \( \( -type f -a \
        \( -name '#*#' -o -name '.*~' -o -name '*~' -o -name DEADJOE \
        -o -name '*.orig' -o -name '*.rej' -o -name '*.bak' \
        -o -name '.*.orig' -o -name .*.rej -o -name '.SUMS' \
        -o -name TAGS -o \( -path '*/.deps/*' -a -name '*.P' \) \
        -o -name config.status -o -name config.cache -o -name config.log \
        \) -exec rm -f "{}" \; \) -o \
        \( -type d -a -name autom4te.cache -prune -exec rm -rf "{}" \; \) \)
    rm intel-driver-$I965_VERSION/.gitignore
    rm intel-driver-$I965_VERSION/.cvsignore
    rm -rf intel-driver-$I965_VERSION/debian.upstream
    rm -rf intel-driver-$I965_VERSION/debian

    # Remove empty directories
    echo "Removing empty directories"
    find intel-driver-$I965_VERSION -type d -empty -delete

    # Repack tarball to final orig tarball
    echo "Creating orig tarball"
    tar --exclude-vcs -zcf "$I965_ORIG_TARBALL" "intel-driver-$I965_VERSION/"
}

make_current_tarball
