.TH ECLIPSE "1" "June 2014" "eclipse 4.4"
.SH NAME
eclipse \- Eclipse IDE for Java Developers
.SH SYNOPSIS
.B eclipse
.SH DESCRIPTION
The Eclipse Platform is an open and extensible platform for anything and yet
nothing in particular. It provides a foundation for constructing and running
integrated software development tools. The Eclipse Platform allows tool
builders to independently develop tools that integrate with other people's
tools so seamlessly you can't tell where one tool ends and another starts.
.SH AUTHOR
Eclipse is Copyright (C) 2014 The Eclipse Foundation.
.PP
This manual page was written by Vincent Cheng <vcheng@debian.org>,
for the Debian project (and may be used by others).
