#!/bin/sh
# postrm script for bumblebee
#
# see: dh_installdeb(1)

set -e


case "$1" in
  purge)
    groupdel bumblebee || true
    for file in bumblebee.conf xorg.conf.nvidia xorg.conf.nouveau; do
        rm -f /etc/bumblebee/$file
    done
    ;;
  remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

  *)
    echo "postrm called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

case "$1" in
  purge|remove|abort-install)
    # update initial ramdisk to skip blacklist
    update-initramfs -u
    ;;
esac

#DEBHELPER#

exit 0
