#!/bin/sh
# preinst script for bumblebee
#
# see: dh_installdeb(1)

set -e

case "$1" in
  install|upgrade)
    # check for ancient versions
    if [ -f /etc/bumblebee ]; then
        cat >&2 <<MSG
An ancient installation of MrMEEE/bumblebee or mj-casalogic/bumblebee has been
detected. To prevent damage, the installation of this version won't be
continued. If you are a novice, you are recommended to reinstall Ubuntu.
MSG
        exit 1
    fi
    ;;

  abort-upgrade)
    ;;

  *)
    echo "preinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

#DEBHELPER#

exit 0
