#!/bin/bash

#Fail on error
set -e

DATA=$AUTOPKGTEST_TMP/data
REPO=$AUTOPKGTEST_TMP/borgrepo

cd $AUTOPKGTEST_TMP

echo "Checking borg is callable"
borg --version

echo "Creating source data dir and mountpoint"
mkdir $DATA

echo "Calling borg init"
borg init --encryption none $REPO

# create source data

echo "Creating $REPO::runone"
echo Hello, world > $DATA/file1
borg create $REPO::runone data/

echo "Creating $REPO::runtwo"
echo Hello again > $DATA/file2
borg create $REPO::runtwo data/

echo "Listing archives"
borg list $REPO

echo "Listing runone and runtwo contents"
borg list $REPO::runone
borg list $REPO::runtwo

echo "Testing borg extract --stdout"
borg extract --stdout $REPO::runtwo data/file1 | grep -q "world"
borg extract --stdout $REPO::runtwo data/file2 | grep -q "again"

echo "All good!"
