#!/bin/sh
set -e

case "$1" in
    configure)
    update-alternatives --install /usr/bin/gnome-www-browser \
           gnome-www-browser /usr/bin/firefox 100
    update-alternatives --install /usr/bin/x-www-browser \
           x-www-browser /usr/bin/firefox 100
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
