#!/bin/sh
set -e

case "$1" in
    remove|upgrade|deconfigure)
    update-alternatives --remove gnome-www-browser /usr/bin/firefox
    update-alternatives --remove x-www-browser /usr/bin/firefox
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
